// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkbsqryxmszognivgdvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYnNxcnl4bXN6b2duaXZnZHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTczOTYsImV4cCI6MjA2NTY3MzM5Nn0.-xN3hNfffQTTDGD3MXtNnakAmO0pTv7RNxFT3R8hIJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);